services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=flow-assignment-fileblocker'
      - 'POSTGRES_USER=flow-user'
      - 'POSTGRES_PASSWORD=flow12!@'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: