services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=file_extension_blocker'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5445:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d file_extension_blocker"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres-data: